$PROBLEM 2-cpt IV compartment-amount reference (ferx-core issue #205)
$DATA iv2.csv IGNORE=@
$INPUT ID TIME DV AMT CMT EVID MDV
$SUBROUTINES ADVAN3 TRANS4
$PK
  CL = THETA(1)
  V1 = THETA(2)
  Q  = THETA(3)
  V2 = THETA(4)
  S1 = V1
$ERROR
  A1 = A(1)
  A2 = A(2)
  IPRED = F
  Y = IPRED + EPS(1)
$THETA 2.0 FIX  10.0 FIX  1.0 FIX  20.0 FIX
$OMEGA 0 FIX
$SIGMA 1 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME A1 A2 IPRED NOPRINT NOAPPEND ONEHEADER FORMAT=,1PE20.10 FILE=iv2.tab
