$PROBLEM 2-cpt oral compartment-amount reference (ferx-core issue #205)
$DATA oral2.csv IGNORE=@
$INPUT ID TIME DV AMT CMT EVID MDV
$SUBROUTINES ADVAN4 TRANS4
$PK
  CL = THETA(1)
  V2 = THETA(2)
  Q  = THETA(3)
  V3 = THETA(4)
  KA = THETA(5)
  S2 = V2
$ERROR
  A1 = A(1)
  A2 = A(2)
  A3 = A(3)
  IPRED = F
  Y = IPRED + EPS(1)
$THETA 2.0 FIX  10.0 FIX  1.0 FIX  20.0 FIX  1.0 FIX
$OMEGA 0 FIX
$SIGMA 1 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME A1 A2 A3 IPRED NOPRINT NOAPPEND ONEHEADER FORMAT=,1PE20.10 FILE=oral2.tab
