$PROBLEM 2-cpt IV time-varying WT with EVID=2 covariate update
$DATA tvcov_intermediate_evid2.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT RATE MDV WT
$SUBROUTINES ADVAN3 TRANS4
$PK
  WTREL = WT / 70
  WTCL  = WTREL ** THETA(5)
  BASECL = THETA(1) * WTCL
  CL = BASECL * EXP(ETA(1))
  V1 = THETA(2)
  QBASE = THETA(3)
  Q = QBASE
  V2BASE = THETA(4)
  V2 = V2BASE
  S1 = V1
$ERROR
  IPRED = F
  Y = IPRED * (1 + EPS(1))
$THETA 10 FIX 50 FIX 15 FIX 100 FIX 0.75 FIX
$OMEGA 0 FIX
$SIGMA 0.04 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID WT PRED IPRED NOPRINT NOAPPEND ONEHEADER FORMAT=,1PE20.10 FILE=tvcov_intermediate_evid2.tab
