//! Tier-3 convergence test for EVID=4 reset (washout) handling on the analytic
//! FOCE/FOCEI gradient path.
//!
//! Exercises the analytical 1-cpt IV reset path end-to-end:
//!   parser → NONMEM CSV reader with EVID=4 rows → fit() to convergence with a
//!   **gradient-based** outer optimizer (`lbfgs`, so the analytic reset gradient
//!   is actually exercised — the default `bobyqa` is gradient-free and would
//!   bypass it) → asserts the optimizer flagged convergence, OFV is finite, and
//!   the recovered typical values are within tolerance of the simulation truth.
//!
//! The dataset (`data/reset_iv_washout.csv`) is generated by the ignored test
//! `generate_reset_iv_washout_dataset` below — run it with
//! `cargo test --no-default-features --features ci --test reset_convergence \
//!  -- --ignored --nocapture`. Each subject has two IV-bolus occasions separated
//! by an EVID=4 reset; the occasions are close enough (12 h, half-life ~7 h) that
//! ~30% of occasion-1 drug would still be present at occasion-2 observations
//! *without* the reset, so the dataset genuinely depends on the reset zeroing the
//! compartment — a superposition regression would mis-predict occasion 2.
//!
//! Gated with `slow-tests` so it runs nightly but is compile-checked on every PR
//! per CLAUDE.md tiering (Tier-3 "runs fit() to convergence").

use ferx_core::parser::model_parser::parse_full_model;
use ferx_core::{fit, read_nonmem_csv};

// Initials are well outside the recovery tolerances so a regression that did no
// effective optimisation would fail. Truth: TVCL=2.0, TVV=20.0.
const RESET_IV_MODEL: &str = r#"
# 1-cpt IV with two EVID=4 washout occasions. Truth: TVCL=2, TVV=20.
# optimizer = nlopt_lbfgs makes the gradient-based path (and thus the analytic reset
# gradient) the one actually exercised; bobyqa (default) is gradient-free.
[parameters]
  theta TVCL(5.0, 0.05, 50.0)
  theta TVV(8.0, 1.0, 200.0)

  omega ETA_CL ~ 0.05
  omega ETA_V  ~ 0.05

  sigma PROP_ERR ~ 0.02 (sd)

[individual_parameters]
  CL = TVCL * exp(ETA_CL)
  V  = TVV  * exp(ETA_V)

[structural_model]
  pk one_cpt_iv(cl=CL, v=V)

[error_model]
  DV ~ proportional(PROP_ERR)

[fit_options]
  method     = focei
  optimizer  = nlopt_lbfgs
  maxiter    = 200
  covariance = false
"#;

#[test]
#[cfg_attr(
    not(feature = "slow-tests"),
    ignore = "slow: opt in with --features slow-tests"
)]
fn fit_runs_on_reset_iv_washout_dataset() {
    let parsed = parse_full_model(RESET_IV_MODEL).expect("reset model parses");
    let model = parsed.model;
    let options = parsed.fit_options;

    let population = read_nonmem_csv(
        std::path::Path::new("data/reset_iv_washout.csv"),
        None,
        None,
    )
    .expect("reset dataset loads");

    assert!(
        population.subjects.iter().any(|s| s.has_resets()),
        "dataset should contain EVID=4 reset rows"
    );

    let result = fit(&model, &population, &model.default_params, &options)
        .expect("reset fit returns a result");

    assert!(
        result.converged,
        "reset fit did not converge (final OFV = {})",
        result.ofv
    );
    assert!(
        result.ofv.is_finite(),
        "OFV = {} should be finite",
        result.ofv
    );

    let theta = &result.theta;
    assert_eq!(theta.len(), 2);
    for (i, v) in theta.iter().enumerate() {
        assert!(v.is_finite() && *v > 0.0, "theta[{i}] = {v} invalid");
    }
    // Truth: TVCL=2.0, TVV=20.0. Initials are 1.5-2.5x off, so these tolerances
    // do real work — a no-op fit would fail. Recovery this tight is only possible
    // if the reset is honoured (otherwise occasion-2 carryover biases CL/V).
    let (tvcl, tvv) = (theta[0], theta[1]);
    assert!(
        (tvcl - 2.0).abs() / 2.0 < 0.20,
        "TVCL recovery: estimated {tvcl:.3}, truth 2.0 (>20% off)"
    );
    assert!(
        (tvv - 20.0).abs() / 20.0 < 0.20,
        "TVV recovery: estimated {tvv:.3}, truth 20.0 (>20% off)"
    );
}

/// Regeneration helper. Ignored by default. Run after changing the 1-cpt IV
/// closed form or reset handling:
///
/// ```sh
/// cargo test --no-default-features --features ci --test reset_convergence \
///   -- --ignored --nocapture generate_reset_iv_washout_dataset
/// ```
///
/// Writes `data/reset_iv_washout.csv` directly from the analytical 1-cpt IV
/// bolus formula (no `simulate()` RNG dependency, so the dataset is
/// deterministic). Each subject has two occasions; occasion 2 is opened by an
/// EVID=4 reset that zeros the compartment, so its observations are computed from
/// the occasion-2 dose alone.
#[test]
#[ignore = "regeneration helper; run with --ignored to rewrite data/reset_iv_washout.csv"]
fn generate_reset_iv_washout_dataset() {
    use ferx_core::pk::one_cpt_iv_bolus;
    use ferx_core::types::DoseEvent;

    let tvcl = 2.0_f64;
    let tvv = 20.0_f64;
    let amt = 100.0_f64;
    let occ2_start = 12.0_f64; // half-life ~7 h → ~30% occ-1 carryover absent reset

    // (eta_cl, eta_v, then a per-observation multiplicative noise factor for the
    // six observations). No RNG — fully deterministic.
    let subjects: &[[f64; 8]] = &[
        [0.00, 0.00, 1.01, 0.99, 1.005, 0.995, 1.008, 0.992],
        [0.12, -0.09, 0.99, 1.02, 0.992, 1.012, 0.996, 1.006],
        [-0.10, 0.11, 1.005, 0.99, 1.015, 0.985, 1.004, 0.996],
        [0.08, 0.05, 0.995, 1.01, 0.99, 1.008, 1.002, 0.994],
        [-0.14, -0.06, 1.012, 0.992, 1.006, 0.994, 0.998, 1.01],
        [0.05, 0.13, 0.99, 1.006, 0.996, 1.004, 1.01, 0.99],
    ];

    // Occasion-local observation times (elapsed since each occasion's dose).
    let occ_obs: &[f64] = &[1.0, 3.0, 6.0];

    let mut csv = String::from("ID,TIME,DV,EVID,AMT,CMT,RATE,MDV\n");
    for (i, row) in subjects.iter().enumerate() {
        let id = i + 1;
        let cl = tvcl * row[0].exp();
        let v = tvv * row[1].exp();
        let noise = &row[2..8];
        let dose = DoseEvent::new(0.0, amt, 1, 0.0, false, 0.0);

        // Occasion 1: ordinary bolus at t=0.
        csv.push_str(&format!("{id},0,.,1,{amt},1,0,1\n"));
        for (j, &tad) in occ_obs.iter().enumerate() {
            let dv = one_cpt_iv_bolus(&dose, tad, cl, v) * noise[j];
            csv.push_str(&format!("{id},{tad},{dv:.6},0,.,1,0,0\n"));
        }
        // Occasion 2: EVID=4 reset + bolus at absolute t=occ2_start; the reset
        // zeros the compartment, so observations rebuild from this dose alone.
        csv.push_str(&format!("{id},{occ2_start},.,4,{amt},1,0,1\n"));
        for (j, &tad) in occ_obs.iter().enumerate() {
            let t_abs = occ2_start + tad;
            let dv = one_cpt_iv_bolus(&dose, tad, cl, v) * noise[3 + j];
            csv.push_str(&format!("{id},{t_abs},{dv:.6},0,.,1,0,0\n"));
        }
    }

    let path = std::path::Path::new("data/reset_iv_washout.csv");
    std::fs::write(path, csv).expect("write data/reset_iv_washout.csv");
    eprintln!("wrote {}", path.display());
}
