//! Tier-2 integration test for steady-state (SS=1) dose handling.
//!
//! Exercises the 1-cpt analytical SS path end-to-end:
//!   parser → NONMEM CSV reader with SS/II columns → fit() with a few
//!   iterations → assert convergence + parameter recovery within tolerance.
//!
//! The dataset (`data/ss_oral_q24.csv`) is generated by the ignored test
//! `generate_ss_oral_q24_dataset` below — run it with
//! `cargo test --no-default-features --features ci --test ss_fit_smoke \
//!  -- --ignored --nocapture` to regenerate.
//!
//! Gated with `slow-tests` so it runs nightly but is compile-checked on
//! every PR per CLAUDE.md tiering.

use ferx_core::parser::model_parser::parse_full_model;
use ferx_core::{fit, read_nonmem_csv};

const SS_ORAL_MODEL: &str = r#"
# 1-cpt oral SS — fits a population on the data generated by
# `generate_ss_oral_q24_dataset`. Truth: TVCL=2, TVV=20, TVKA=1.5.
[parameters]
  theta TVCL(2.5, 0.01, 50.0)
  theta TVV(15.0, 0.5, 200.0)
  theta TVKA(1.0, 0.05, 20.0)

  omega ETA_CL ~ 0.05
  omega ETA_V  ~ 0.05
  omega ETA_KA ~ 0.1

  sigma PROP_ERR ~ 0.02 (sd)

[individual_parameters]
  CL = TVCL * exp(ETA_CL)
  V  = TVV  * exp(ETA_V)
  KA = TVKA * exp(ETA_KA)

[structural_model]
  pk one_cpt_oral(cl=CL, v=V, ka=KA)

[error_model]
  DV ~ proportional(PROP_ERR)

[fit_options]
  method     = foce
  maxiter    = 50
  covariance = false
"#;

#[test]
#[cfg_attr(
    not(feature = "slow-tests"),
    ignore = "slow: opt in with --features slow-tests"
)]
fn fit_runs_on_ss_oral_dataset() {
    let parsed = parse_full_model(SS_ORAL_MODEL).expect("SS model parses");
    let model = parsed.model;
    let options = parsed.fit_options;

    let population = read_nonmem_csv(std::path::Path::new("data/ss_oral_q24.csv"), None, None)
        .expect("SS dataset loads");

    assert!(
        population.subjects.iter().any(|s| s.has_ss_doses()),
        "dataset should contain SS=1 doses"
    );

    let result =
        fit(&model, &population, &model.default_params, &options).expect("SS fit returns a result");

    // Smoke-level assertions: the fit reached a finite estimate and moved
    // off the (intentionally biased) initial values.
    let theta = &result.theta;
    assert_eq!(theta.len(), 3);
    for (i, v) in theta.iter().enumerate() {
        assert!(v.is_finite(), "theta[{}] = {} is not finite", i, v);
        assert!(*v > 0.0, "theta[{}] = {} is non-positive", i, v);
    }
    assert!(
        result.ofv.is_finite(),
        "OFV = {} should be finite",
        result.ofv
    );

    // Truth: TVCL=2.0, TVV=20.0, TVKA=1.5. With realistic residual noise we
    // expect recovery within ~25% on a 4-subject dataset and 50 iterations.
    // Loose tolerance — this is a smoke test, not a convergence test.
    let (tvcl, tvv, tvka) = (theta[0], theta[1], theta[2]);
    assert!(
        (tvcl - 2.0).abs() / 2.0 < 0.30,
        "TVCL recovery: estimated {:.3}, truth 2.0 (>30% off)",
        tvcl
    );
    assert!(
        (tvv - 20.0).abs() / 20.0 < 0.30,
        "TVV recovery: estimated {:.3}, truth 20.0 (>30% off)",
        tvv
    );
    assert!(
        (tvka - 1.5).abs() / 1.5 < 0.40,
        "TVKA recovery: estimated {:.3}, truth 1.5 (>40% off)",
        tvka
    );
}

/// Regeneration helper. Ignored by default so it doesn't run in CI. Run
/// manually after changing the SS closed forms (e.g.):
///
/// ```sh
/// cargo test --no-default-features --features ci --test ss_fit_smoke \
///   -- --ignored --nocapture generate_ss_oral_q24_dataset
/// ```
///
/// Writes `data/ss_oral_q24.csv` using the analytical 1-cpt oral SS
/// formula directly — no `simulate()` dependency, so the dataset stays
/// deterministic across changes to the simulation RNG.
#[test]
#[ignore = "regeneration helper; run with --ignored to rewrite data/ss_oral_q24.csv"]
fn generate_ss_oral_q24_dataset() {
    use ferx_core::pk::one_cpt_oral_ss;
    use ferx_core::types::DoseEvent;

    // 4 subjects with hand-picked etas (no RNG — fully deterministic).
    // Each subject is at steady state under q24h dosing of AMT=100.
    let tvcl = 2.0_f64;
    let tvv = 20.0_f64;
    let tvka = 1.5_f64;
    let amt = 100.0_f64;
    let ii = 24.0_f64;

    // (eta_cl, eta_v, eta_ka, prop_err_scale_per_obs)
    let subjects: &[[f64; 7]] = &[
        // Subject 1: typical values (zero etas), 1% noise
        [0.0, 0.0, 0.0, 1.01, 0.98, 1.005, 0.995],
        // Subject 2: slightly above-average CL, below-average V
        [0.10, -0.08, 0.05, 0.99, 1.02, 0.995, 1.015],
        // Subject 3: below-average CL, above-average V
        [-0.12, 0.10, -0.05, 1.005, 0.99, 1.02, 0.985],
        // Subject 4: faster absorption, typical disposition
        [0.0, 0.0, 0.20, 0.995, 1.01, 0.985, 1.005],
    ];

    let obs_times: &[f64] = &[1.0, 4.0, 12.0, 23.0];

    let mut csv = String::from("ID,TIME,DV,EVID,AMT,CMT,RATE,MDV,II,SS\n");

    for (i, row) in subjects.iter().enumerate() {
        let id = i + 1;
        let cl = tvcl * row[0].exp();
        let v = tvv * row[1].exp();
        let ka = tvka * row[2].exp();
        let noise = &row[3..7];

        // Dose record: SS=1, II=24, AMT=100 at t=0.
        csv.push_str(&format!("{},0,.,1,{},1,0,1,{},1\n", id, amt, ii));

        // Observation records.
        let dose = DoseEvent::new(0.0, amt, 1, 0.0, true, ii);
        for (j, &t) in obs_times.iter().enumerate() {
            let dv_true = one_cpt_oral_ss(&dose, t, cl, v, ka);
            let dv = dv_true * noise[j];
            csv.push_str(&format!("{},{},{:.6},0,.,1,0,0,.,.\n", id, t, dv));
        }
    }

    let path = std::path::Path::new("data/ss_oral_q24.csv");
    std::fs::write(path, csv).expect("write data/ss_oral_q24.csv");
    eprintln!("wrote {}", path.display());
}
