//! Tier-3 convergence test for time-varying covariate handling on the analytic
//! FOCE/FOCEI gradient path.
//!
//! Exercises the analytical 1-cpt oral TV-covariate path end-to-end:
//!   parser → NONMEM CSV reader (a `WT` column that changes within each subject,
//!   so the reader emits per-event covariate snapshots and `has_tv_covariates()`)
//!   → fit() to convergence with a **gradient-based** outer optimizer (`lbfgs`, so
//!   the analytic TV-cov gradient is actually exercised — the default `bobyqa` is
//!   gradient-free and would bypass it) → asserts the optimizer flagged
//!   convergence, OFV is finite, and the recovered typical values (incl. the
//!   allometric WT-on-CL exponent THETA_WT) are within tolerance of the simulation
//!   truth.
//!
//! The dataset (`data/tvcov_oral_wt.csv`) is generated by the ignored test
//! `generate_tvcov_oral_dataset` below — run it with
//! `cargo test --no-default-features --features ci --test tvcov_convergence \
//!  -- --ignored --nocapture generate_tvcov_oral_dataset`. `WT` steps up twice
//! within each subject (at 6 h and 12 h), so the covariate genuinely varies over
//! the decay and the data depends on the per-event parameter switching the
//! event-driven walk performs — a static-covariate regression would mis-predict
//! the late observations.
//!
//! Gated with `slow-tests` so it runs nightly but is compile-checked on every PR
//! per CLAUDE.md tiering (Tier-3 "runs fit() to convergence").

use ferx_core::parser::model_parser::parse_full_model;
use ferx_core::{fit, read_nonmem_csv};

// Initials are well off the recovery tolerances so a regression that did no
// effective optimisation would fail. Truth: TVCL=0.15, TVV=8.0, TVKA=1.0,
// THETA_WT=0.75. `optimizer = nlopt_lbfgs` makes the gradient-based path (and thus
// the analytic TV-cov gradient) the one actually exercised.
const TVCOV_ORAL_MODEL: &str = r#"
# 1-cpt oral with allometric WT-on-CL. Truth: TVCL=0.15, TVV=8, TVKA=1, THETA_WT=0.75.
[parameters]
  theta TVCL(0.3, 0.01, 10.0)
  theta TVV(15.0, 1.0, 200.0)
  theta TVKA(1.8, 0.05, 20.0)
  theta THETA_WT(0.4, 0.01, 2.0)

  omega ETA_CL ~ 0.05
  omega ETA_V  ~ 0.05

  sigma PROP_ERR ~ 0.01 (sd)

[individual_parameters]
  CL = TVCL * (WT/70)^THETA_WT * exp(ETA_CL)
  V  = TVV  * exp(ETA_V)
  KA = TVKA

[structural_model]
  pk one_cpt_oral(cl=CL, v=V, ka=KA)

[covariates]
  WT continuous

[error_model]
  DV ~ proportional(PROP_ERR)

[fit_options]
  method     = focei
  optimizer  = nlopt_lbfgs
  maxiter    = 200
  covariance = false
"#;

// Per subject: baseline WT, WT step (applied at 6 h and again at 12 h), ETA_CL,
// ETA_V. Shared by the generator and documented here so the truth is auditable.
const SUBJECTS: &[(f64, f64, f64, f64)] = &[
    (52.0, 6.0, 0.00, 0.00),
    (61.0, 8.0, 0.10, -0.08),
    (70.0, 10.0, -0.09, 0.07),
    (78.0, -6.0, 0.06, 0.05),
    (86.0, 9.0, -0.12, -0.05),
    (95.0, -8.0, 0.05, 0.11),
    (66.0, 12.0, -0.04, -0.10),
    (90.0, 7.0, 0.08, 0.03),
];
const TADS: &[f64] = &[0.5, 1.0, 2.0, 4.0, 6.0, 9.0, 12.0, 18.0, 24.0];

// WT time course: two LOCF step changes, at 6 h and 12 h.
fn wt_at(base: f64, step: f64, t: f64) -> f64 {
    base + if t >= 6.0 { step } else { 0.0 } + if t >= 12.0 { step } else { 0.0 }
}

#[test]
#[cfg_attr(
    not(feature = "slow-tests"),
    ignore = "slow: opt in with --features slow-tests"
)]
fn fit_runs_on_tvcov_oral_dataset() {
    let parsed = parse_full_model(TVCOV_ORAL_MODEL).expect("tvcov model parses");
    let model = parsed.model;
    let options = parsed.fit_options;

    let population = read_nonmem_csv(std::path::Path::new("data/tvcov_oral_wt.csv"), None, None)
        .expect("tvcov dataset loads");

    assert!(
        population.subjects.iter().any(|s| s.has_tv_covariates()),
        "dataset should carry time-varying covariate snapshots"
    );

    let result = fit(&model, &population, &model.default_params, &options)
        .expect("tvcov fit returns a result");

    assert!(
        result.converged,
        "tvcov fit did not converge (final OFV = {})",
        result.ofv
    );
    assert!(
        result.ofv.is_finite(),
        "OFV = {} should be finite",
        result.ofv
    );

    let theta = &result.theta;
    assert_eq!(theta.len(), 4);
    for (i, v) in theta.iter().enumerate() {
        assert!(v.is_finite() && *v > 0.0, "theta[{i}] = {v} invalid");
    }
    // Truth: TVCL=0.15, TVV=8.0, TVKA=1.0, THETA_WT=0.75. Initials are 1.8-2.4x
    // off, so these tolerances do real work. THETA_WT (the covariate coefficient)
    // gets a looser band — its identifiability rests on the across-subject WT
    // spread, weaker than the structural θ's.
    let (tvcl, tvv, tvka, wt_exp) = (theta[0], theta[1], theta[2], theta[3]);
    assert!(
        (tvcl - 0.15).abs() / 0.15 < 0.20,
        "TVCL recovery: estimated {tvcl:.4}, truth 0.15 (>20% off)"
    );
    assert!(
        (tvv - 8.0).abs() / 8.0 < 0.20,
        "TVV recovery: estimated {tvv:.3}, truth 8.0 (>20% off)"
    );
    assert!(
        (tvka - 1.0).abs() / 1.0 < 0.25,
        "TVKA recovery: estimated {tvka:.3}, truth 1.0 (>25% off)"
    );
    assert!(
        (wt_exp - 0.75).abs() / 0.75 < 0.30,
        "THETA_WT recovery: estimated {wt_exp:.3}, truth 0.75 (>30% off)"
    );
}

/// Regeneration helper. Ignored by default. Run after changing the 1-cpt oral
/// closed form or the TV-covariate event-driven walk:
///
/// ```sh
/// cargo test --no-default-features --features ci --test tvcov_convergence \
///   -- --ignored --nocapture generate_tvcov_oral_dataset
/// ```
///
/// Writes `data/tvcov_oral_wt.csv`. The DV is the **production** TV-covariate
/// predictor (`compute_predictions_with_tv`) evaluated per subject at deterministic
/// etas (no RNG → deterministic dataset), with a small deterministic multiplicative
/// perturbation so residuals are nonzero. A throwaway CSV is read first so the real
/// covariate plumbing (LOCF per-event snapshots) builds the subjects exactly as the
/// fit will.
#[test]
#[ignore = "regeneration helper; run with --ignored to rewrite data/tvcov_oral_wt.csv"]
fn generate_tvcov_oral_dataset() {
    use ferx_core::pk::compute_predictions_with_tv;

    let truth = [0.15_f64, 8.0, 1.0, 0.75]; // TVCL, TVV, TVKA, THETA_WT

    // 1) Throwaway CSV with the WT time course + placeholder DV, so the reader
    //    builds per-event covariate snapshots the same way the fit will.
    let mut seed_csv = String::from("ID,TIME,DV,EVID,AMT,CMT,RATE,MDV,WT\n");
    for (i, &(base, step, _, _)) in SUBJECTS.iter().enumerate() {
        let id = i + 1;
        let wt0 = wt_at(base, step, 0.0);
        seed_csv.push_str(&format!("{id},0,.,1,100,1,0,1,{wt0}\n"));
        for &tad in TADS {
            let wt = wt_at(base, step, tad);
            seed_csv.push_str(&format!("{id},{tad},1,0,.,1,0,0,{wt}\n"));
        }
    }
    let tmp = std::env::temp_dir().join("ferx_tvcov_seed.csv");
    std::fs::write(&tmp, &seed_csv).expect("write seed csv");

    let parsed = parse_full_model(TVCOV_ORAL_MODEL).expect("model parses");
    let model = parsed.model;
    let pop = read_nonmem_csv(&tmp, None, None).expect("seed csv loads");

    // 2) Re-emit with model-predicted DV (+ small deterministic noise).
    let mut out = String::from("ID,TIME,DV,EVID,AMT,CMT,RATE,MDV,WT\n");
    for (i, (s, &(base, step, ecl, ev))) in pop.subjects.iter().zip(SUBJECTS.iter()).enumerate() {
        let id = &s.id;
        let eta = [ecl, ev];
        let preds = compute_predictions_with_tv(&model, s, &truth, &eta);
        let wt0 = wt_at(base, step, 0.0);
        out.push_str(&format!("{id},0,.,1,100,1,0,1,{wt0}\n"));
        for (j, &tad) in TADS.iter().enumerate() {
            let wt = wt_at(base, step, tad);
            // Deterministic ±~1.5% multiplicative noise (no RNG).
            let n = ((j as f64 * 1.7 + i as f64 * 2.3).sin()) * 0.015;
            let dv = preds[j] * (1.0 + n);
            out.push_str(&format!("{id},{tad},{dv:.6},0,.,1,0,0,{wt}\n"));
        }
    }

    let path = std::path::Path::new("data/tvcov_oral_wt.csv");
    std::fs::write(path, out).expect("write data/tvcov_oral_wt.csv");
    eprintln!("wrote {}", path.display());
}
