# Fit the Gompertz TTE dataset with nlmixr2 (reference fit for ferx Phase 1).
#
# Requires: nlmixr2, rxode2
# Dataset:  tte_gompertz.csv (generated by simulate.R)
#
# Fixed-effects model (no ETA) to match nlmixr2 blog structure.
# Uses bobyqa (derivative-free) as in the blog reference.
#
# Run:  Rscript nlmixr2.R
#       Paste key output into expected.md

library(nlmixr2)

dat <- read.csv("tte_gompertz.csv")
names(dat)[names(dat) == "ID"]   <- "id"
names(dat)[names(dat) == "DV"]   <- "event"
names(dat)[names(dat) == "TIME"] <- "time"
# TRT column is a covariate — keep as-is; nlmixr2 will find it in the data.

gompertz_model <- function() {
  ini({
    log_alpha <- -6.0    # init near true value
    log_gamma <- -5.4
    log_hr    <- -0.8
  })
  model({
    alpha <- exp(log_alpha)
    gamma <- exp(log_gamma)
    h     <- alpha * exp(gamma * time) * exp(log_hr * TRT)
    H     <- (alpha / gamma) * (exp(gamma * time) - 1) * exp(log_hr * TRT)
    ll(tte) ~ event * log(h) - H
  })
}

fit <- nlmixr(gompertz_model, dat, est = "bobyqa",
              control = bobyqaControl(print = 5))

print(fit)
cat("\n--- Key values for expected.md ---\n")
cat(sprintf("OFV (-2LL):   %.4f\n", fit$objective))
cat(sprintf("AIC:          %.4f\n", fit$AIC))
cat(sprintf("log_alpha:    %.4f  SE %.4f\n",
            fixef(fit)["log_alpha"], sqrt(fit$varFix["log_alpha", "log_alpha"])))
cat(sprintf("log_gamma:    %.4f  SE %.4f\n",
            fixef(fit)["log_gamma"], sqrt(fit$varFix["log_gamma", "log_gamma"])))
cat(sprintf("log_hr:       %.4f  SE %.4f\n",
            fixef(fit)["log_hr"],    sqrt(fit$varFix["log_hr", "log_hr"])))

# Also try focei for comparison with ferx default method
cat("\n--- FOCEI fit ---\n")
fit_focei <- nlmixr(gompertz_model, dat, est = "focei",
                    control = foceiControl(print = 5))
cat(sprintf("OFV (-2LL):   %.4f\n", fit_focei$objective))
cat(sprintf("log_alpha:    %.4f\n", fixef(fit_focei)["log_alpha"]))
cat(sprintf("log_gamma:    %.4f\n", fixef(fit_focei)["log_gamma"]))
cat(sprintf("log_hr:       %.4f\n", fixef(fit_focei)["log_hr"]))
