# Fit the Gompertz TTE dataset with nlmixr2 (reference fit for ferx Phase 1).
#
# Requires: nlmixr2, rxode2
# Dataset:  tte_gompertz.csv (generated by simulate.R)
#
# Fixed-effects model (no ETA) matching the nlmixr2 blog structure. The blog uses
# `est = "bobyqa"`, but that fails to fit this TTE model in nlmixr2 5.x, so this
# script uses FOCEI — and for a fixed-effects model FOCEI reduces to plain ML.
#
# Run:  Rscript nlmixr2.R
#       Paste key output into expected.md

library(nlmixr2)

dat <- read.csv("tte_gompertz.csv")
# Keep the standard DV/TIME columns (nlmixr2 requires them); the ll(tte) model
# references an `event` column, so mirror DV into it. TRT stays as a covariate.
dat$event <- dat$DV

gompertz_model <- function() {
  ini({
    log_alpha <- -6.0    # init near true value
    log_gamma <- -5.4
    log_hr    <- -0.8
  })
  model({
    alpha <- exp(log_alpha)
    gamma <- exp(log_gamma)
    h     <- alpha * exp(gamma * time) * exp(log_hr * TRT)
    H     <- (alpha / gamma) * (exp(gamma * time) - 1) * exp(log_hr * TRT)
    ll(tte) ~ event * log(h) - H
  })
}

# NB: `est = "bobyqa"` (as in the nlmixr2 blog) fails to fit this TTE model in
# nlmixr2 5.x; FOCEI is used instead (fixed-effects, so FOCEI == plain ML here).
fit <- nlmixr(gompertz_model, dat, est = "focei",
              control = foceiControl(print = 5))

print(fit)
cat("\n--- Key values for expected.md ---\n")
cat(sprintf("OFV (-2LL):   %.4f\n", fit$objective))
cat(sprintf("AIC:          %.4f\n", fit$AIC))
cat(sprintf("log_alpha:    %.4f  SE %.4f\n",
            fixef(fit)["log_alpha"], sqrt(fit$varFix["log_alpha", "log_alpha"])))
cat(sprintf("log_gamma:    %.4f  SE %.4f\n",
            fixef(fit)["log_gamma"], sqrt(fit$varFix["log_gamma", "log_gamma"])))
cat(sprintf("log_hr:       %.4f  SE %.4f\n",
            fixef(fit)["log_hr"],    sqrt(fit$varFix["log_hr", "log_hr"])))
