# Fit the Weibull TTE dataset with nlmixr2 (reference fit for ferx Phase 1).
#
# Requires: nlmixr2, rxode2
# Dataset:  tte_weibull.csv (generated by simulate.R)
#
# Model uses scale parameterization: H(t) = (t/scale)^shape
# h(t) = (shape/scale) * (t/scale)^(shape-1)
#
# Run:  Rscript nlmixr2.R

library(nlmixr2)

dat <- read.csv("tte_weibull.csv")   # ID,TIME,DV,EVID,CMT,MDV ; DV = event indicator
# Keep the standard DV/TIME columns (nlmixr2 requires them); the ll(tte) model
# references an `event` column, so mirror DV into it.
dat$event <- dat$DV

weibull_model <- function() {
  ini({
    log_scale <- log(20)
    log_shape <- log(2)
    eta.shape ~ 0.20
  })
  model({
    scale <- exp(log_scale)
    shape <- exp(log_shape + eta.shape)
    h <- (shape / scale) * (time / scale)^(shape - 1)
    H <- (time / scale)^shape
    ll(tte) ~ event * log(h) - H
  })
}

fit <- nlmixr(weibull_model, dat, est = "focei",
              control = foceiControl(print = 5))

print(fit)
cat("\n--- Key values for expected.md ---\n")
cat(sprintf("OFV (-2LL):   %.4f\n", fit$objective))
cat(sprintf("AIC:          %.4f\n", fit$AIC))
cat(sprintf("log_scale:    %.4f  SE %.4f\n",
            fixef(fit)["log_scale"], sqrt(fit$varFix["log_scale", "log_scale"])))
cat(sprintf("log_shape:    %.4f  SE %.4f\n",
            fixef(fit)["log_shape"], sqrt(fit$varFix["log_shape", "log_shape"])))
cat(sprintf("omega_shape (var): %.4f\n", fit$omega["eta.shape", "eta.shape"]))
