# Fit the Exponential TTE dataset with nlmixr2 (reference fit for ferx Phase 1).
#
# Requires: nlmixr2, rxode2  (install.packages("nlmixr2"))
# Dataset:  tte_exp.csv  (generated by simulate.R in this directory)
#
# Run:  Rscript nlmixr2.R
#       Paste key output into expected.md

library(nlmixr2)

dat <- read.csv("tte_exp.csv")   # ID,TIME,DV,EVID,CMT,MDV ; DV = event indicator (1=event,0=cens)
# nlmixr2 needs the standard DV/TIME columns present; the ll(tte) model references an
# `event` column, so mirror DV into it (keep DV/TIME so nlmixr2's data check passes).
dat$event <- dat$DV

expo_model <- function() {
  ini({
    log_lambda <- log(0.1)
    eta.lambda ~ 0.25
  })
  model({
    lambda <- exp(log_lambda + eta.lambda)
    h      <- lambda
    H      <- lambda * time
    ll(tte) ~ event * log(h) - H
  })
}

fit <- nlmixr(expo_model, dat, est = "focei",
              control = foceiControl(print = 5))

print(fit)
cat("\n--- Key values for expected.md ---\n")
cat(sprintf("OFV (-2LL):  %.4f\n", fit$objective))
cat(sprintf("AIC:         %.4f\n", fit$AIC))
cat(sprintf("log_lambda:  %.4f  SE %.4f\n",
            fixef(fit)["log_lambda"], sqrt(fit$varFix["log_lambda", "log_lambda"])))
cat(sprintf("omega_lambda (var): %.4f\n", fit$omega["eta.lambda", "eta.lambda"]))
