[book]
title = "FeRx-NLME Documentation"
authors = ["InsightRx"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/FeRx-NLME/ferx-core"
additional-js = ["mathjax-config.js"]
