[book]
title = "ferx-core Documentation"
authors = ["Teun Post", "Ron Keizer"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/FeRx-NLME/ferx-core"
additional-js = ["mathjax-config.js"]
